services:
  app:
    build: .
    ports:
      - '8080:8080'
      - '5555:5555' # for browsing db with prisma studio
    volumes:
      - .:/app
      - backend-node-modules:/app/node_modules
      # - ./storage:/tmp
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/send-suite
    depends_on:
      - db
  reverse-proxy:
    image: nginx:latest
    volumes:
      - ./tls-dev-proxy/nginx.conf:/etc/nginx/nginx.conf
      - ./tls-dev-proxy/certs:/etc/ssl/certs
      - ./tls-dev-proxy/logs:/var/log/nginx
    ports:
      - '8088:12345'
    depends_on:
      - app
  db:
    image: 'postgres:15'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - '6432:5432'

volumes:
  postgres-data:
  backend-node-modules: