services:
  app:
    build: .
    ports:
      - "80:8080"
    volumes:
      - .:/app
      - ./storage:/tmp
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/send-suite
    depends_on:
      - db
    restart: unless-stopped
  db:
    image: "postgres:15"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "6432:5432"
    restart: unless-stopped

volumes:
  postgres-data:
