version: "3.8"

services:
  # app:
  #   build: .
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - DATABASE_URL=postgres://postgres:secret@db:5432/postgres
  #     - REDIS_URL=redis://redis:6379
  #   depends_on:
  #     - db
  #     - redis
  reverse-proxy:
    image: nginx:latest
    container_name: reverse-proxy
    ports:
      - "8088:12345"
    volumes:
      - ./tls-dev-proxy/nginx.conf:/etc/nginx/nginx.conf
      - ./tls-dev-proxy/certs:/etc/ssl/certs
      - ./tls-dev-proxy/logs:/var/log/nginx
    restart: unless-stopped
  db:
    image: "postgres:15"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  redis:
    image: "redis:7"
    ports:
      - 6379:6379

volumes:
  postgres-data:
