---
resources:
  tb:network:MultiCidrVpc:
    vpc:
      cidr_block: 10.0.0.0/16
      enable_dns_hostnames: True
      endpoint_interfaces:
        - ecr.api
        - ecr.dkr
        - logs
        - secretsmanager
        - ssm
      endpoint_gateways:
        - s3
      subnets:
        us-east-1a:
          - 10.0.101.0/24
        us-east-1b:
          - 10.0.102.0/24
        us-east-1c:
          - 10.0.103.0/24

  tb:network:SecurityGroupWithRules:
    backend:
     rules:
        ingress:
          - cidr_blocks: ['0.0.0.0/0']
            description: Backend port
            protocol: tcp
            from_port: 8080
            to_port: 8080
          - cidr_blocks: ['0.0.0.0/0']
            description: Prisma Studio port
            protocol: tcp
            from_port: 5555
            to_port: 5555
        egress:
          - cidr_blocks: ['0.0.0.0/0']
            description: Outbound TLS traffic
            protocol: tcp
            from_port: 0
            to_port: 65535

  tb:secrets:PulumiSecretsManager:
    pulumi:
      secret_names:
        - b2-application-key-id
        - b2-application-key
        - fxa-client-id
        - fxa-client-secret

  tb:rds:RdsDatabaseGroup:
    backend:
      engine_version: 15.7  # 16.x is available, but it's in beta and only supported in certain configs
      instance_class: db.t3.micro
      num_instances: 1
      parameter_group_family: postgres15
      skip_final_snapshot: True
      # Jumphost options
      build_jumphost: False
      # jumphost_public_key: ''
      # jumphost_source_cidrs: ['']
      # jumphost_user_data: |
      #   #!/bin/bash
      #   yum update -y
      #   yum install -y postgresql15

  tb:fargate:FargateClusterWithLogging:
    backend:
      internal: False
      ecr_resources:
        - arn:aws:ecr:us-east-1:768512802988:repository/send*
      task_definition:
        network_mode: awsvpc
        cpu: 512
        memory: 1024
        requires_compatibilities:
          - FARGATE
        container_definitions:
          backend:
            image: 768512802988.dkr.ecr.us-east-1.amazonaws.com/send:staging
            portMappings:
              - name: send-suite
                containerPort: 8080
                hostPort: 8080
                protocol: tcp
                appProtocol: http
              - name: prisma
                containerPort: 5555
                hostPort: 5555
                protocol: tcp
                appProtocol: http
            linuxParameters:
              initProcessEnabled: True
            secrets:
              - name: B2_APPLICATION_KEY
                valueFrom: arn:aws:secretsmanager:us-east-1:768512802988:secret:send-suite/staging/b2-application-key-OfJfMS
              - name: B2_APPLICATION_KEY_ID
                valueFrom: arn:aws:secretsmanager:us-east-1:768512802988:secret:send-suite/staging/b2-application-key-id-5QFZWv
              - name: DATABASE_URL
                valueFrom: arn:aws:secretsmanager:us-east-1:768512802988:secret:send-suite/staging/database_url-5c8zAR
              - name: FXA_CLIENT_ID
                valueFrom: arn:aws:secretsmanager:us-east-1:768512802988:secret:send-suite/staging/fxa-client-id-trDR1r
              - name: FXA_CLIENT_SECRET
                valueFrom: arn:aws:secretsmanager:us-east-1:768512802988:secret:send-suite/staging/fxa-client-secret-FGcei3
            environment:
              - name: APP_ENV
                value: DEV
              - name: B2_BUCKET_NAME
                value: tb-send-staging
              - name: B2_ENDPOINT
                value: s3.eu-central-003.backblazeb2.com
              - name: B2_REGION
                value: auto
              - name: BASE_URL
                value: https://thunderbird.dev:8088
              - name: COMBINED_LOG
                value: logs/combined.log
              - name: DEVELOPER_TIMEZONE
                value: US/Eastern
              - name: DATABASE_ENGINE
                value: postgres
              - name: DATABASE_USER
                value: sendapp
              - name: ERROR_LOG
                value: logs/error.log
              - name: FS_LOCAL_BUCKET
                value: send-fs-local
              - name: FXA_ENTRYPOINT
                value: tblockbox
              - name: FXA_METRICS_FLOW_URL
                value: https://accounts.stage.mozaws.net/metrics-flow
              - name: FXA_MOZ_ISSUER
                value: https://accounts.stage.mozaws.net
              - name: FXA_REDIRECT_URI
                value: http://lockbox.thunderbird.dev:5173/lockbox/fxa
              - name: STORAGE_BACKEND
                value: b2
      services:
        send-suite:
          listener_port: 443
          listener_proto: HTTPS
          listener_cert_arn: arn:aws:acm:us-east-1:768512802988:certificate/3a98e226-c4df-4e58-bc0a-aa4ccbf6325e
          container_port: 8080
          container_name: backend
          # "name" field is arbitrary, but must be unique and no longer than 32 chars
          name: send-suite-staging-api
        # prisma:
        #   listener_port: 5555
        #   container_port: 5555
        #   container_name: backend
        #   name: send-suite-staging-prisma