export const CONTAINER_TYPE = {
  CONVERSATION: 'CONVERSATION',
  FOLDER: 'FOLDER',
};

export const ITEM_TYPE = {
  MESSAGE: 'MESSAGE',
  FILE: 'FILE',
};

export const EXTENSION_READY = 'EXTENSION_READY';
export const SHARE_COMPLETE = 'SHARE_COMPLETE';
export const SHARE_ABORTED = 'SHARE_ABORTED';
