name: Test Coverage

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10.6.4

      - name: Install dependencies
        run: pnpm install

      - name: Run frontend tests with coverage
        run: cd packages/send/frontend && pnpm run test:coverage

      - name: Run backend tests with coverage
        run: cd packages/send/backend && pnpm run test:coverage

      - name: Run E2E tests with coverage
        run: cd packages/send && pnpm run test:e2e:coverage:ci

      - name: Combine coverage reports
        run: |
          mkdir -p combined-coverage
          cp -r packages/send/frontend/coverage/* combined-coverage/
          cp -r packages/send/backend/coverage/* combined-coverage/
          cp -r packages/send/coverage/* combined-coverage/

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: combined-coverage
          fail_ci_if_error: true
