---
name: validate

concurrency:
  group: validate
  cancel-in-progress: true

on:
  push:
    branches:
      - "**"
      - "!main"

permissions:
  contents: read

jobs:
  # When the backend code changes, run these steps
  backend-tests:
    runs-on: ubuntu-latest
    env:
      IS_CI_AUTOMATION: "yes"
    strategy:
      matrix:
        node-version: ["22"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        id: install-dependencies
        shell: bash
        run: |
          npm install -g pnpm
          npm install -g bun
          pnpm install

      - name: Backend tests
        id: backend-tests
        shell: bash
        run: |
          cd backend
          cp .env.sample .env

          # Certain values here contain "/" characters, which need to be escaped so sed doesn't break
          APP_KEY=$(echo '${{ secrets.TEST_B2_APPLICATION_KEY }}' | sed 's/\//\\\//g')
          B2_ENDPOINT=$(echo '${{ vars.TEST_B2_ENDPOINT }}' | sed 's/\//\\\//g')
          S3_ENDPOINT=$(echo '${{ secrets.TEST_S3_ENDPOINT }}' | sed 's/\//\\\//g')

          sed -i "s/^TEST_B2_REGION=$/TEST_B2_REGION=${{ vars.TEST_B2_REGION }}/" .env
          sed -i "s/^TEST_B2_ENDPOINT=$/TEST_B2_ENDPOINT=$B2_ENDPOINT/" .env
          sed -i "s/^TEST_B2_APPLICATION_KEY=$/TEST_B2_APPLICATION_KEY=$APP_KEY/" .env
          sed -i "s/^TEST_B2_BUCKET_NAME=$/TEST_B2_BUCKET_NAME=${{ vars.TEST_B2_BUCKET_NAME }}/" .env
          sed -i "s/^TEST_B2_APPLICATION_KEY_ID=$/TEST_B2_APPLICATION_KEY_ID=${{ secrets.TEST_B2_APPLICATION_KEY_ID }}/" .env
          sed -i "s/^TEST_S3_REGION=$/TEST_S3_REGION=${{ secrets.TEST_S3_REGION }}/" .env
          sed -i "s/^TEST_S3_ENDPOINT=$/TEST_S3_ENDPOINT=$S3_ENDPOINT/" .env
          sed -i "s/^TEST_S3_ACCESS_KEY=$/TEST_S3_ACCESS_KEY=${{ secrets.TEST_S3_ACCESS_KEY }}/" .env
          sed -i "s/^TEST_S3_SECRET_KEY=$/TEST_S3_SECRET_KEY=${{ secrets.TEST_S3_SECRET_KEY }}/" .env
          sed -i "s/^TEST_S3_BUCKET_NAME=$/TEST_S3_BUCKET_NAME=${{ secrets.TEST_S3_BUCKET_NAME }}/" .env

          cd ..

          cd frontend
          cat << EOF > .env
          VUE_BASE_URL=http://localhost:5173
          VITE_SEND_SERVER_URL=https://localhost:8088
          VITE_SEND_CLIENT_URL=http://localhost:5173
          VITE_SENTRY_AUTH_TOKEN=${{ secrets.VITE_SENTRY_AUTH_TOKEN }}
          VITE_SENTRY_DSN=${{ vars.VITE_SENTRY_DSN }}
          VITE_POSTHOG_PROJECT_KEY=${{ secrets.VITE_POSTHOG_PROJECT_KEY }}
          VITE_POSTHOG_HOST=${{ vars.VITE_POSTHOG_HOST }}
          EOF

          cd ..

      - name: Run stack and test
        id: run-stack-and-test
        shell: bash
        run: |
          pnpm test:e2e:ci
