---
name: validate

concurrency:
  group: validate
  cancel-in-progress: true

on:
  push:
    branches:
      - "**"
      - "!main"

permissions:
  contents: read

jobs:
  # When the backend code changes, run these steps
  end-to-end-tests:
    runs-on: ubuntu-latest
    env:
      IS_CI_AUTOMATION: "yes"
    strategy:
      matrix:
        node-version: ["22"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        id: install-dependencies
        shell: bash
        run: |
          npm install -g pnpm
          npm install -g bun
          pnpm install

      # - name: Install Playwright Browsers
      #   run: pnpx playwright install --with-deps

      - name: E2E tests
        id: set-up-e2e
        shell: bash
        run: |
          cd backend
          cp .env.sample .env

          cd ..

          cd frontend
          cp .env.sample .env
          cd ..

      - name: Run stack and test
        id: run-stack-and-test
        shell: bash
        run: |
          pnpm test:e2e:ci

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/index.html
          retention-days: 30
